from dataclasses import dataclass
from dataclasses import field
from typing import Any
from typing import Dict
from typing import FrozenSet
from typing import List
from typing import Optional
from typing import Set
from typing import Tuple
from typing import cast

import numpy as np

from sde.core.domain import Trial
from sde.core.domain import TrialStatus


@dataclass
class Insight:
    """A structured, human-readable conclusion generated by the engine."""

    message: str
    type: str
    trial_ids: List[str] = field(default_factory=list)


class InsightEngine:
    """Analyze the state of an experiment to find and report insights."""

    def __init__(
        self, trials: Dict[str, Trial], primary_metric: str, higher_is_better: bool
    ):
        """Initialize the insight engine."""
        self.trials = trials
        self.primary_metric = primary_metric
        self.higher_is_better = higher_is_better
        self.current_best_trial_id: Optional[str] = None
        self._fired_plateau_insights: Set[str] = set()
        self._fired_poor_start_insights: Set[str] = set()
        self._fired_crossover_insights: Set[Tuple[FrozenSet[str], str]] = set()
        self._fired_correlation_insights: Set[str] = set()

    def analyze_on_epoch(self, active_trial: Trial) -> List[Insight]:
        """Run all insight detectors that should trigger after each epoch."""
        detectors = [
            self._detect_best_performer,
            self._detect_performance_crossover,
            self._detect_performance_plateau,
            self._detect_poor_initial_performance,
        ]
        return self._run_detectors(detectors, active_trial)

    def analyze_on_finish(self, finished_trial: Trial) -> List[Insight]:
        """Run all insight detectors that should trigger after a trial finishes."""
        detectors = [self._detect_hyperparameter_correlation]
        return self._run_detectors(detectors, finished_trial)

    def _run_detectors(self, detectors: list, trial: Trial) -> List[Insight]:
        all_insights = []
        for detector in detectors:
            result = detector(trial)
            if result:
                if isinstance(result, list):
                    all_insights.extend(result)
                else:
                    all_insights.append(result)
        return all_insights

    def _detect_best_performer(self, trial: Trial) -> Optional[Insight]:
        try:
            finished_trial_perf = trial.results[self.primary_metric][-1][1]
        except (KeyError, IndexError):
            return None
        current_best_perf = -1.0
        if self.current_best_trial_id and self.current_best_trial_id in self.trials:
            best_trial = self.trials[self.current_best_trial_id]
            try:
                current_best_perf = best_trial.results[self.primary_metric][-1][1]
            except (KeyError, IndexError):
                pass
        is_new_best = (
            self.higher_is_better and finished_trial_perf > current_best_perf
        ) or (not self.higher_is_better and finished_trial_perf < current_best_perf)
        if is_new_best and trial.id != self.current_best_trial_id:
            self.current_best_trial_id = trial.id
            message = (
                f"New best performer! Trial {trial.id[:6]} has reached "
                f"{finished_trial_perf:.4f} {self.primary_metric}."
            )
            return Insight(
                message=message,
                type="BEST_PERFORMER",
                trial_ids=[trial.id],
            )
        return None

    def _get_perf_at_epoch(self, trial_id: str, epoch: int) -> Optional[float]:
        if trial_id not in self.trials:
            return None
        try:
            return cast(
                float,
                next(
                    p
                    for e, p in self.trials[trial_id].results[self.primary_metric]
                    if e == epoch
                ),
            )
        except (KeyError, StopIteration):
            return None

    def _detect_performance_crossover(self, active_trial: Trial) -> List[Insight]:
        insights = []
        try:
            current_epoch = active_trial.current_epoch
            if current_epoch < 1:
                return []
            active_perf_now = self._get_perf_at_epoch(active_trial.id, current_epoch)
            active_perf_prev = self._get_perf_at_epoch(
                active_trial.id, current_epoch - 1
            )
            if active_perf_now is None or active_perf_prev is None:
                return []
            for other_trial in self.trials.values():
                if other_trial.id == active_trial.id:
                    continue
                other_perf_now = self._get_perf_at_epoch(other_trial.id, current_epoch)
                other_perf_prev = self._get_perf_at_epoch(
                    other_trial.id, current_epoch - 1
                )
                if other_perf_now is None or other_perf_prev is None:
                    continue
                prev_delta = active_perf_prev - other_perf_prev
                now_delta = active_perf_now - other_perf_now
                if prev_delta * now_delta < 0:
                    winner_id, loser_id = (
                        (active_trial.id, other_trial.id)
                        if now_delta > 0
                        else (other_trial.id, active_trial.id)
                    )
                    if not self.higher_is_better:
                        winner_id, loser_id = loser_id, winner_id
                    crossover_key = (
                        frozenset([active_trial.id, other_trial.id]),
                        winner_id,
                    )
                    if crossover_key not in self._fired_crossover_insights:
                        self._fired_crossover_insights.add(crossover_key)
                        message = (
                            f"Performance Crossover: Trial {winner_id[:6]} has "
                            f"overtaken {loser_id[:6]} at epoch {current_epoch}."
                        )
                        insights.append(
                            Insight(
                                message=message,
                                type="PERFORMANCE_CROSSOVER",
                                trial_ids=[active_trial.id, other_trial.id],
                            )
                        )
        except (KeyError, IndexError):
            return []
        return insights

    def _detect_performance_plateau(
        self, trial: Trial, lookback: int = 4, relative_tolerance: float = 0.005
    ) -> Optional[Insight]:
        try:
            history = [val for _, val in trial.results[self.primary_metric]]
            if len(history) < lookback:
                return None
            last_value = history[-1]
            past_value = history[-lookback]
            if abs(past_value) < 1e-9:
                return None
            improvement = (last_value - past_value) / abs(past_value)
            if not self.higher_is_better:
                improvement = -improvement
            if improvement < relative_tolerance:
                if trial.id not in self._fired_plateau_insights:
                    self._fired_plateau_insights.add(trial.id)
                    message = (
                        f"Warning: Trial {trial.id[:6]}'s performance may have "
                        "plateaued."
                    )
                    return Insight(
                        message=message,
                        type="PLATEAU",
                        trial_ids=[trial.id],
                    )
            elif trial.id in self._fired_plateau_insights:
                self._fired_plateau_insights.remove(trial.id)
        except (KeyError, IndexError):
            return None
        return None

    def _get_completed_trials_with_results(self, min_trials: int) -> List[Trial]:
        completed = [
            t
            for t in self.trials.values()
            if t.status in {TrialStatus.COMPLETED, TrialStatus.PRUNED}
            and self.primary_metric in t.results
        ]
        return completed if len(completed) >= min_trials else []

    def _flatten_hyperparameters(
        self, trials: List[Trial]
    ) -> Dict[str, Dict[str, Any]]:
        flat_hparams: Dict[str, Dict[str, Any]] = {}
        for trial in trials:
            flat_hparams[trial.id] = {}
            for p_type, params in trial.hyperparameters.items():
                for p_name, p_value in params.items():
                    p_value_key = (
                        tuple(p_value) if isinstance(p_value, list) else p_value
                    )
                    flat_hparams[trial.id][f"{p_type}.{p_name}"] = p_value_key
        return flat_hparams

    def _get_varied_hyperparameters(
        self, flat_hparams: Dict[str, Dict[str, Any]]
    ) -> set[str]:
        if not flat_hparams:
            return set()
        varied_hparams = set()
        first_trial_params = list(flat_hparams.values())[0]
        for param_name in first_trial_params:
            unique_values = {
                trial_params.get(param_name) for trial_params in flat_hparams.values()
            }
            if len(unique_values) > 1:
                varied_hparams.add(param_name)
        return varied_hparams

    def _group_trials_by_hparam(
        self,
        hparam_name: str,
        flat_hparams: Dict[str, Dict[str, Any]],
        min_group_size: int,
    ) -> Dict[Any, List[str]]:
        groups: Dict[Any, List[str]] = {}
        first_value = list(flat_hparams.values())[0][hparam_name]
        is_numeric = isinstance(first_value, (int, float))
        if is_numeric:
            values = [p[hparam_name] for p in flat_hparams.values() if hparam_name in p]
            if len(values) < min_group_size * 2:
                return {}
            try:
                bins = np.quantile(values, [0.33, 0.66])
                for trial_id, params in flat_hparams.items():
                    val = params.get(hparam_name)
                    if val is None:
                        continue
                    if val <= bins[0]:
                        group_name = "low"
                    elif val > bins[1]:
                        group_name = "high"
                    else:
                        group_name = "medium"
                    groups.setdefault(group_name, []).append(trial_id)
            except IndexError:
                return {}
        else:
            for trial_id, params in flat_hparams.items():
                group_name = params.get(hparam_name, "N/A")
                groups.setdefault(group_name, []).append(trial_id)
        return groups

    def _detect_hyperparameter_correlation(
        self,
        finished_trial: Trial,
        min_trials_for_correlation: int = 5,
        min_group_size: int = 3,
        significance_threshold: float = 0.1,
    ) -> List[Insight]:
        completed_trials = self._get_completed_trials_with_results(
            min_trials_for_correlation
        )
        if not completed_trials:
            return []
        flat_hparams = self._flatten_hyperparameters(completed_trials)
        varied_hparams = self._get_varied_hyperparameters(flat_hparams)
        insights = []
        for hparam_name in varied_hparams:
            if hparam_name in self._fired_correlation_insights:
                continue
            groups = self._group_trials_by_hparam(
                hparam_name, flat_hparams, min_group_size
            )
            group_perfs = {}
            for name, trial_ids in groups.items():
                if len(trial_ids) >= min_group_size:
                    perf = [
                        self.trials[tid].results[self.primary_metric][-1][1]
                        for tid in trial_ids
                    ]
                    group_perfs[name] = sum(perf) / len(perf)
            if len(group_perfs) < 2:
                continue
            sorted_groups = sorted(
                group_perfs.items(),
                key=lambda item: item[1],
                reverse=self.higher_is_better,
            )
            best_group_name, best_group_perf = sorted_groups[0]
            worst_group_name, worst_group_perf = sorted_groups[-1]
            relative_diff = abs(best_group_perf - worst_group_perf) / (
                abs(worst_group_perf) + 1e-9
            )
            if relative_diff > significance_threshold:
                all_involved_ids = [tid for g in groups.values() for tid in g]
                message = (
                    f"Correlation found for '{hparam_name}': group "
                    f"'{best_group_name}' (avg perf: {best_group_perf:.3f}) "
                    f"outperforms group '{worst_group_name}' "
                    f"(avg perf: {worst_group_perf:.3f})."
                )
                insights.append(
                    Insight(
                        message=message,
                        type="HYPERPARAM_CORRELATION",
                        trial_ids=all_involved_ids,
                    )
                )
                self._fired_correlation_insights.add(hparam_name)
        return insights

    def _detect_poor_initial_performance(
        self, trial: Trial, z_score_threshold: float = 2.0
    ) -> Optional[Insight]:
        try:
            if trial.current_epoch != 1:
                return None
            if trial.id in self._fired_poor_start_insights:
                return None
            own_perf = trial.results[self.primary_metric][-1][1]
            peer_performances = []
            for other_trial in self.trials.values():
                if other_trial.id == trial.id or other_trial.current_epoch < 1:
                    continue
                try:
                    peer_perf = next(
                        p for e, p in other_trial.results[self.primary_metric] if e == 1
                    )
                    peer_performances.append(peer_perf)
                except (KeyError, StopIteration):
                    continue
            if len(peer_performances) < 2:
                return None
            mean_perf = sum(peer_performances) / len(peer_performances)
            std_dev = (
                sum([(p - mean_perf) ** 2 for p in peer_performances])
                / len(peer_performances)
            ) ** 0.5
            if std_dev < 1e-9:
                return None
            z_score = (own_perf - mean_perf) / std_dev
            is_poor_outlier = (
                self.higher_is_better and z_score < -z_score_threshold
            ) or (not self.higher_is_better and z_score > z_score_threshold)
            if is_poor_outlier:
                self._fired_poor_start_insights.add(trial.id)
                message = (
                    f"Warning: Trial {trial.id[:6]} is performing poorly "
                    f"({own_perf:.4f}) compared to its peers (avg: {mean_perf:.4f}) "
                    "after the first epoch."
                )
                return Insight(
                    message=message,
                    type="POOR_INITIAL_PERFORMANCE",
                    trial_ids=[trial.id],
                )
        except (KeyError, IndexError):
            return None
        return None
