from dataclasses import dataclass
from typing import List, Dict, Optional

from sde.core.types import Trial

@dataclass
class Insight:
    """A structured, human-readable conclusion generated by the engine."""
    message: str
    type: str # e.g., "BEST_PERFORMER", "PLATEAU"

class InsightEngine:
    """
    Analyzes the state of an experiment to find and report insights.
    """
    def __init__(self, trials: Dict[str, Trial], primary_metric: str, higher_is_better: bool):
        self.trials = trials
        self.primary_metric = primary_metric
        self.higher_is_better = higher_is_better
        self.current_best_trial_id: Optional[str] = None

    def analyze(self, finished_trial: Trial) -> List[Insight]:
        """
        Runs all insight detectors and returns a list of new insights.
        """
        insights = []

        # Run detectors
        best_performer_insight = self._detect_best_performer(finished_trial)
        if best_performer_insight:
            insights.append(best_performer_insight)

        plateau_insight = self._detect_performance_plateau(finished_trial)
        if plateau_insight:
            insights.append(plateau_insight)

        return insights

    def _detect_best_performer(self, finished_trial: Trial) -> Optional[Insight]:
        """
        Checks if the finished trial is now the best-performing trial overall.
        """
        try:
            finished_trial_perf = finished_trial.results[self.primary_metric][-1][1]
        except (KeyError, IndexError):
            return None # Not enough data for this trial

        current_best_perf = -1.0
        if self.current_best_trial_id and self.current_best_trial_id in self.trials:
            best_trial = self.trials[self.current_best_trial_id]
            try:
                current_best_perf = best_trial.results[self.primary_metric][-1][1]
            except (KeyError, IndexError):
                pass # The old best trial might not have data anymore

        # If the finished trial is better than the current best, we have a new leader
        is_new_best = False
        if self.higher_is_better and finished_trial_perf > current_best_perf:
            is_new_best = True
        elif not self.higher_is_better and finished_trial_perf < current_best_perf:
            is_new_best = True

        if is_new_best and finished_trial.id != self.current_best_trial_id:
            self.current_best_trial_id = finished_trial.id
            return Insight(
                message=f"New best performer! Trial {finished_trial.id[:6]} has reached {finished_trial_perf:.4f} {self.primary_metric}.",
                type="BEST_PERFORMER"
            )
        return None

    def _detect_performance_plateau(self, trial: Trial, lookback: int = 3, tolerance: float = 0.001) -> Optional[Insight]:
        """
        Checks if a trial's performance has not improved significantly over the last few epochs.
        """
        try:
            history = [val for epoch, val in trial.results[self.primary_metric]]
            if len(history) < lookback:
                return None # Not enough data

            recent_history = history[-lookback:]
            improvement = max(recent_history) - min(recent_history) if self.higher_is_better else max(recent_history) - min(recent_history)

            if abs(improvement) < tolerance:
                # To avoid spamming, only fire this insight once per plateau
                if not hasattr(trial, '_plateau_insight_fired'):
                    trial._plateau_insight_fired = True
                    return Insight(
                        message=f"Warning: Trial {trial.id[:6]}'s performance has plateaued.",
                        type="PLATEAU"
                    )
            else:
                # Reset the flag if performance improves again
                if hasattr(trial, '_plateau_insight_fired'):
                    del trial._plateau_insight_fired

        except (KeyError, IndexError):
            return None

        return None
