from dataclasses import dataclass
from typing import List, Optional

from sde.core.types import Trial, TrialStatus
from sde.engine.datastore import DataStore

@dataclass
class Insight:
    """A structured, human-readable conclusion generated by the engine."""
    message: str
    type: str

class InsightEngine:
    """
    Analyzes the state of an experiment to find and report insights.
    This version uses a more robust internal state to avoid duplicate insights
    and has more reliable logic for detecting the best performer.
    """
    def __init__(self, datastore: DataStore, primary_metric: str, higher_is_better: bool):
        self.datastore = datastore
        self.primary_metric = primary_metric
        self.higher_is_better = higher_is_better
        self.current_best_trial_id: Optional[str] = None
        # A set to track fired insights and prevent duplicates, storing (trial_id, insight_type)
        self._fired_insights = set()

    def analyze(self, finished_trial: Trial) -> List[Insight]:
        """Runs all insight detectors and returns a list of new insights."""
        detectors = [
            self._detect_best_performer,
            self._detect_performance_plateau,
            self._detect_poor_initial_performance,
        ]
        insights = []
        for detector in detectors:
            insight = detector(finished_trial)
            if insight:
                insights.append(insight)
        return insights

    def _has_fired(self, trial_id: str, insight_type: str) -> bool:
        """Checks if a specific insight type has already been fired for a trial."""
        return (trial_id, insight_type) in self._fired_insights

    def _mark_fired(self, trial_id: str, insight_type: str):
        """Marks an insight type as fired for a trial."""
        self._fired_insights.add((trial_id, insight_type))

    def _detect_best_performer(self, finished_trial: Trial) -> Optional[Insight]:
        """Checks if the finished trial is now the best-performing trial overall."""
        try:
            finished_trial_perf = finished_trial.results[self.primary_metric][-1][1]
        except (KeyError, IndexError):
            return None

        # Find the best performance among all active trials, excluding the finished one.
        best_other_perf = None
        active_trials = self.datastore.get_trials_by_status(TrialStatus.ACTIVE)
        for trial in active_trials:
            if trial.id == finished_trial.id:
                continue
            try:
                perf = trial.results[self.primary_metric][-1][1]
                if best_other_perf is None or (self.higher_is_better and perf > best_other_perf) or \
                   (not self.higher_is_better and perf < best_other_perf):
                    best_other_perf = perf
            except (KeyError, IndexError):
                continue

        is_new_best = False
        if best_other_perf is None:
            is_new_best = True # This is the first trial to report a result.
        elif self.higher_is_better and finished_trial_perf > best_other_perf:
            is_new_best = True
        elif not self.higher_is_better and finished_trial_perf < best_other_perf:
            is_new_best = True

        if is_new_best and finished_trial.id != self.current_best_trial_id:
            self.current_best_trial_id = finished_trial.id
            return Insight(
                message=f"New best performer! Trial {finished_trial.id[:6]} has reached {finished_trial_perf:.4f} {self.primary_metric}.",
                type="BEST_PERFORMER"
            )
        return None

    def _detect_performance_plateau(self, trial: Trial, lookback: int = 4, relative_tolerance: float = 0.005) -> Optional[Insight]:
        """Checks if a trial's performance has not improved significantly over recent epochs."""
        insight_type = "PLATEAU"
        if self._has_fired(trial.id, insight_type):
            return None
        try:
            history = [val for _, val in trial.results[self.primary_metric]]
            if len(history) < lookback:
                return None

            last_value = history[-1]
            past_value = history[-lookback]

            if abs(past_value) < 1e-9:
                return None

            improvement = (last_value - past_value) / abs(past_value)
            if not self.higher_is_better:
                improvement = -improvement

            if improvement < relative_tolerance:
                self._mark_fired(trial.id, insight_type)
                return Insight(
                    message=f"Warning: Trial {trial.id[:6]}'s performance may have plateaued.",
                    type=insight_type
                )
        except (KeyError, IndexError):
            return None
        return None

    def _detect_poor_initial_performance(self, trial: Trial, z_score_threshold: float = 2.0) -> Optional[Insight]:
        """Checks if a trial's performance after its first epoch is a significant outlier."""
        insight_type = "POOR_INITIAL_PERFORMANCE"
        if trial.current_epoch != 1 or self._has_fired(trial.id, insight_type):
            return None
        try:
            own_perf = trial.results[self.primary_metric][-1][1]
            peer_performances = []
            for other_trial in self.datastore.get_all_trials():
                if other_trial.id == trial.id or other_trial.current_epoch < 1:
                    continue
                try:
                    peer_perf = next(p for e, p in other_trial.results[self.primary_metric] if e == 1)
                    peer_performances.append(peer_perf)
                except (KeyError, StopIteration):
                    continue

            if len(peer_performances) < 2:
                return None

            mean_perf = sum(peer_performances) / len(peer_performances)
            std_dev = (sum([(p - mean_perf) ** 2 for p in peer_performances]) / len(peer_performances)) ** 0.5
            if std_dev < 1e-9: return None

            z_score = (own_perf - mean_perf) / std_dev
            is_poor_outlier = (self.higher_is_better and z_score < -z_score_threshold) or \
                              (not self.higher_is_better and z_score > z_score_threshold)

            if is_poor_outlier:
                self._mark_fired(trial.id, insight_type)
                return Insight(
                    message=f"Warning: Trial {trial.id[:6]} is performing poorly ({own_perf:.4f}) compared to its peers (avg: {mean_perf:.4f}) after the first epoch.",
                    type=insight_type
                )
        except (KeyError, IndexError):
            return None
        return None
