import numpy as np
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any

from sde.core.types import Trial, TrialStatus

@dataclass
class Insight:
    """A structured, human-readable conclusion generated by the engine."""
    message: str
    type: str  # e.g., "BEST_PERFORMER", "PLATEAU"
    # A list of trial IDs relevant to this insight for UI interactivity
    trial_ids: List[str] = field(default_factory=list)

class InsightEngine:
    """
    Analyzes the state of an experiment to find and report insights.
    """
    def __init__(self, trials: Dict[str, Trial], primary_metric: str, higher_is_better: bool):
        self.trials = trials
        self.primary_metric = primary_metric
        self.higher_is_better = higher_is_better
        self.current_best_trial_id: Optional[str] = None
        # Internal state to track fired insights and avoid spam
        self._fired_plateau_insights = set()
        self._fired_poor_start_insights = set()
        self._fired_crossover_insights = set()
        self._fired_correlation_insights = set()


    def analyze(self, finished_trial: Trial) -> List[Insight]:
        """
        Runs all insight detectors and returns a list of new insights.
        """
        detectors = [
            self._detect_best_performer,
            self._detect_performance_crossover,
            self._detect_performance_plateau,
            self._detect_poor_initial_performance,
            self._detect_hyperparameter_correlation,
        ]

        all_insights = []
        for detector in detectors:
            # Detectors can return a single insight, a list of insights, or None
            result = detector(finished_trial)
            if result:
                if isinstance(result, list):
                    all_insights.extend(result)
                else:
                    all_insights.append(result)
        return all_insights

    def _detect_best_performer(self, finished_trial: Trial) -> Optional[Insight]:
        """
        Checks if the finished trial is now the best-performing trial overall.
        """
        try:
            finished_trial_perf = finished_trial.results[self.primary_metric][-1][1]
        except (KeyError, IndexError):
            return None # Not enough data for this trial

        current_best_perf = -1.0
        if self.current_best_trial_id and self.current_best_trial_id in self.trials:
            best_trial = self.trials[self.current_best_trial_id]
            try:
                current_best_perf = best_trial.results[self.primary_metric][-1][1]
            except (KeyError, IndexError):
                pass # The old best trial might not have data anymore

        # If the finished trial is better than the current best, we have a new leader
        is_new_best = False
        if self.higher_is_better and finished_trial_perf > current_best_perf:
            is_new_best = True
        elif not self.higher_is_better and finished_trial_perf < current_best_perf:
            is_new_best = True

        if is_new_best and finished_trial.id != self.current_best_trial_id:
            self.current_best_trial_id = finished_trial.id
            return Insight(
                message=f"New best performer! Trial {finished_trial.id[:6]} has reached {finished_trial_perf:.4f} {self.primary_metric}.",
                type="BEST_PERFORMER",
                trial_ids=[finished_trial.id]
            )
        return None

    def _get_perf_at_epoch(self, trial_id: str, epoch: int) -> Optional[float]:
        """A helper to safely get performance at a specific epoch."""
        if trial_id not in self.trials:
            return None
        try:
            # Find the result for the specific epoch
            return next(p for e, p in self.trials[trial_id].results[self.primary_metric] if e == epoch)
        except (KeyError, StopIteration):
            return None

    def _detect_performance_crossover(self, active_trial: Trial) -> List[Insight]:
        """
        Checks if the active trial has just overtaken another trial in performance.
        """
        insights = []
        try:
            current_epoch = active_trial.current_epoch
            if current_epoch < 1:
                return []

            active_perf_now = self._get_perf_at_epoch(active_trial.id, current_epoch)
            active_perf_prev = self._get_perf_at_epoch(active_trial.id, current_epoch - 1)

            if active_perf_now is None or active_perf_prev is None:
                return [] # Not enough history for the active trial

            for other_trial in self.trials.values():
                if other_trial.id == active_trial.id:
                    continue

                # To avoid detecting the same crossover twice, only the trial with the lexicographically smaller ID is responsible for detection
                if active_trial.id > other_trial.id:
                    continue

                other_perf_now = self._get_perf_at_epoch(other_trial.id, current_epoch)
                other_perf_prev = self._get_perf_at_epoch(other_trial.id, current_epoch - 1)

                if other_perf_now is None or other_perf_prev is None:
                    continue # Not enough history for the other trial to compare

                # Check for crossover event (handles both increasing and decreasing metrics)
                prev_delta = active_perf_prev - other_perf_prev
                now_delta = active_perf_now - other_perf_now

                # Crossover happens if the sign of the performance delta flips
                if prev_delta * now_delta < 0:
                    # Determine winner/loser based on metric direction
                    winner_id, loser_id = (active_trial.id, other_trial.id) if now_delta > 0 else (other_trial.id, active_trial.id)
                    if not self.higher_is_better:
                        winner_id, loser_id = loser_id, winner_id

                    crossover_pair = frozenset([active_trial.id, other_trial.id])
                    if crossover_pair not in self._fired_crossover_insights:
                        self._fired_crossover_insights.add(crossover_pair)
                        insights.append(Insight(
                            message=f"Performance Crossover: Trial {winner_id[:6]} has overtaken {loser_id[:6]} at epoch {current_epoch}.",
                            type="PERFORMANCE_CROSSOVER",
                            trial_ids=[active_trial.id, other_trial.id]
                        ))
        except (KeyError, IndexError):
            return [] # Should not happen with the guards in place, but good practice

        return insights


    def _detect_performance_plateau(self, trial: Trial, lookback: int = 4, relative_tolerance: float = 0.005) -> Optional[Insight]:
        """
        Checks if a trial's performance has not improved significantly over recent epochs.
        Uses a relative tolerance to be robust to different metric scales.
        """
        try:
            history = [val for _, val in trial.results[self.primary_metric]]
            if len(history) < lookback:
                return None  # Not enough data

            # Get the most recent value and the value from 'lookback' epochs ago
            last_value = history[-1]
            past_value = history[-lookback]

            # Avoid division by zero if the past value was 0
            if abs(past_value) < 1e-9:
                return None

            # Calculate relative improvement
            improvement = (last_value - past_value) / abs(past_value)

            # If we expect the metric to decrease, a positive improvement is bad
            if not self.higher_is_better:
                improvement = -improvement

            if improvement < relative_tolerance:
                # To avoid spamming, only fire this insight once per plateau
                if trial.id not in self._fired_plateau_insights:
                    self._fired_plateau_insights.add(trial.id)
                    return Insight(
                        message=f"Warning: Trial {trial.id[:6]}'s performance may have plateaued.",
                        type="PLATEAU",
                        trial_ids=[trial.id]
                    )
            else:
                # Reset the flag if performance improves again
                if trial.id in self._fired_plateau_insights:
                    self._fired_plateau_insights.remove(trial.id)

        except (KeyError, IndexError):
            return None

        return None

    def _get_completed_trials_with_results(self, min_trials: int) -> List[Trial]:
        """Returns a list of completed or pruned trials that have results."""
        completed = [t for t in self.trials.values() if t.status in {TrialStatus.COMPLETED, TrialStatus.PRUNED} and self.primary_metric in t.results]
        return completed if len(completed) >= min_trials else []

    def _flatten_hyperparameters(self, trials: List[Trial]) -> Dict[str, Dict[str, Any]]:
        """Converts the nested hyperparameter structure to a flat dictionary for easier analysis."""
        flat_hparams = {}
        for trial in trials:
            flat_hparams[trial.id] = {}
            for p_type, params in trial.hyperparameters.items():
                for p_name, p_value in params.items():
                    # Handle unhashable types like lists
                    p_value_key = tuple(p_value) if isinstance(p_value, list) else p_value
                    flat_hparams[trial.id][f"{p_type}.{p_name}"] = p_value_key
        return flat_hparams

    def _get_varied_hyperparameters(self, flat_hparams: Dict[str, Dict[str, Any]]) -> set[str]:
        """Identifies which hyperparameters have more than one unique value across all trials."""
        if not flat_hparams:
            return set()

        varied_hparams = set()
        first_trial_params = list(flat_hparams.values())[0]
        for param_name in first_trial_params:
            unique_values = {trial_params.get(param_name) for trial_params in flat_hparams.values()}
            if len(unique_values) > 1:
                varied_hparams.add(param_name)
        return varied_hparams

    def _group_trials_by_hparam(self, hparam_name: str, flat_hparams: Dict[str, Dict[str, Any]], min_group_size: int) -> Dict[Any, List[str]]:
        """Groups trials based on the value of a specific hyperparameter, binning numerical ones."""
        groups: Dict[Any, List[str]] = {}
        first_value = list(flat_hparams.values())[0][hparam_name]
        # Treat numbers as numeric; everything else (strings, tuples, etc.) as categorical
        is_numeric = isinstance(first_value, (int, float))

        if is_numeric:
            values = [p[hparam_name] for p in flat_hparams.values() if hparam_name in p]
            if len(values) < min_group_size * 2: return {}
            try:
                # Bin numerical data into 3 groups: low, medium, high
                bins = np.quantile(values, [0.33, 0.66])
                for trial_id, params in flat_hparams.items():
                    val = params.get(hparam_name)
                    if val is None: continue
                    group_name = "low" if val <= bins[0] else "high" if val > bins[1] else "medium"
                    groups.setdefault(group_name, []).append(trial_id)
            except IndexError:
                return {} # Not enough data to form quantiles
        else: # Categorical
            for trial_id, params in flat_hparams.items():
                group_name = params.get(hparam_name, "N/A")
                groups.setdefault(group_name, []).append(trial_id)

        return groups

    def _detect_hyperparameter_correlation(self, finished_trial: Trial, min_trials_for_correlation: int = 5, min_group_size: int = 3, significance_threshold: float = 0.1) -> List[Insight]:
        """Analyzes completed trials to find correlations between hyperparameters and performance."""
        completed_trials = self._get_completed_trials_with_results(min_trials_for_correlation)
        if not completed_trials:
            return []

        flat_hparams = self._flatten_hyperparameters(completed_trials)
        varied_hparams = self._get_varied_hyperparameters(flat_hparams)
        insights = []

        for hparam_name in varied_hparams:
            if hparam_name in self._fired_correlation_insights:
                continue

            groups = self._group_trials_by_hparam(hparam_name, flat_hparams, min_group_size)

            group_perfs = {}
            for name, trial_ids in groups.items():
                if len(trial_ids) >= min_group_size:
                    perf = [self.trials[tid].results[self.primary_metric][-1][1] for tid in trial_ids]
                    group_perfs[name] = sum(perf) / len(perf)

            if len(group_perfs) < 2:
                continue

            sorted_groups = sorted(group_perfs.items(), key=lambda item: item[1], reverse=self.higher_is_better)
            best_group_name, best_group_perf = sorted_groups[0]
            worst_group_name, worst_group_perf = sorted_groups[-1]

            relative_diff = abs(best_group_perf - worst_group_perf) / (abs(worst_group_perf) + 1e-9)
            if relative_diff > significance_threshold:
                all_involved_ids = [tid for g in groups.values() for tid in g]
                insights.append(Insight(
                    message=f"Correlation found for '{hparam_name}': group '{best_group_name}' (avg perf: {best_group_perf:.3f}) outperforms group '{worst_group_name}' (avg perf: {worst_group_perf:.3f}).",
                    type="HYPERPARAM_CORRELATION",
                    trial_ids=all_involved_ids
                ))
                self._fired_correlation_insights.add(hparam_name)

        return insights

    def _detect_poor_initial_performance(self, trial: Trial, z_score_threshold: float = 2.0) -> Optional[Insight]:
        """
        Checks if a trial's performance after its first epoch is a significant outlier.
        """
        try:
            # Only run this check for the first epoch result
            if trial.current_epoch != 1:
                return None

            # Avoid firing this insight more than once
            if trial.id in self._fired_poor_start_insights:
                return None

            own_perf = trial.results[self.primary_metric][-1][1]

            # Gather performance of other trials at the same point (1 epoch)
            peer_performances = []
            for other_trial in self.trials.values():
                if other_trial.id == trial.id or other_trial.current_epoch < 1:
                    continue
                try:
                    # Find the result for the first epoch
                    peer_perf = next(p for e, p in other_trial.results[self.primary_metric] if e == 1)
                    peer_performances.append(peer_perf)
                except (KeyError, StopIteration):
                    continue # No data for this peer at epoch 1

            if len(peer_performances) < 2:
                return None # Not enough peers to form a meaningful comparison

            # Calculate Z-score
            mean_perf = sum(peer_performances) / len(peer_performances)
            std_dev = (sum([(p - mean_perf) ** 2 for p in peer_performances]) / len(peer_performances)) ** 0.5

            if std_dev < 1e-9:
                return None # Avoid division by zero if all peers have the same performance

            z_score = (own_perf - mean_perf) / std_dev

            # If higher is better, a large negative z-score is bad.
            # If lower is better, a large positive z-score is bad.
            is_poor_outlier = (self.higher_is_better and z_score < -z_score_threshold) or \
                              (not self.higher_is_better and z_score > z_score_threshold)

            if is_poor_outlier:
                self._fired_poor_start_insights.add(trial.id)
                return Insight(
                    message=f"Warning: Trial {trial.id[:6]} is performing poorly ({own_perf:.4f}) compared to its peers (avg: {mean_perf:.4f}) after the first epoch.",
                    type="POOR_INITIAL_PERFORMANCE",
                    trial_ids=[trial.id]
                )

        except (KeyError, IndexError):
            return None

        return None
