from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field
from enum import Enum
from typing import Any
from typing import Callable
from typing import Tuple
from typing import Type

import torch.nn as nn


class SdeModel(nn.Module):
    """Base class for all models in the Scientific Discovery Engine.
    It standardizes the model interface across different architectures.
    """

    def __init__(self, input_shape: Tuple[int, ...], output_shape: int, **kwargs):
        super().__init__()
        self.input_shape = input_shape
        self.output_shape = output_shape


class DatasetType(Enum):
    """Enum to categorize the type of a dataset.
    This is used to ensure that models are only used with compatible datasets.
    """

    IMAGE_CLASSIFICATION = "IMAGE_CLASSIFICATION"
    TABULAR_REGRESSION = "TABULAR_REGRESSION"


@dataclass(frozen=True)
class DatasetDefinition:
    """A metadata container for a dataset, treated as a static definition."""

    name: str
    type: DatasetType
    description: str
    loader_factory: Callable[..., Tuple[Any, Any]]  # Returns (train, val) loaders
    input_shape: Tuple[int, ...]  # e.g., (1, 28, 28) for MNIST
    output_shape: int  # Number of output classes or features
    loss_function_factory: Callable[[], Any]
    performance_metric_name: str  # e.g., "accuracy"


@dataclass(frozen=True)
class ModelDefinition:
    """A metadata container for a model/algorithm, treated as a static definition."""

    name: str
    description: str
    model_class: Type[SdeModel]
    model_type: DatasetType  # The type of dataset this model is designed for
    hyperparameter_schema: dict = field(default_factory=dict)


class InsightType(Enum):
    """The type of a scientific insight generated by the engine."""

    HYPERPARAM_CORRELATION = "HYPERPARAM_CORRELATION"
    PLATEAU_DETECTED = "PLATEAU_DETECTED"
    PERFORMANCE_CROSSOVER = "PERFORMANCE_CROSSOVER"
    ANOMALOUS_PERFORMANCE = "ANOMALOUS_PERFORMANCE"


@dataclass(frozen=True)
class Insight:
    """A structured, human-readable conclusion generated by the Insight Engine."""

    type: InsightType
    content: str
    trial_ids: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        """Serializes the Insight to a dictionary."""
        return {
            "type": self.type.value,
            "content": self.content,
            "trial_ids": self.trial_ids,
        }

    @classmethod
    def from_dict(cls, d: dict) -> Insight:
        """Creates an Insight from a dictionary."""
        return cls(
            type=InsightType(d["type"]),
            content=d["content"],
            trial_ids=d.get("trial_ids", []),
        )
